- name: Manven install
  ansible.builtin.dnf: 
    name: maven
    state: installed

- name: import app-prerequisites tasks
  ansible.builtin.import_tasks: app_prerequisite.yml

- name: MVN clean 
  ansible.builtin.shell: mvn clean package ;  mv target/{{component}}-1.0.jar {{component}}.jar 
  args:
    chdir: /app
  
- name: import mysql tasks
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: import systemd setup
  ansible.builtin.import_tasks: systemd-setup.yml