
- name: Rabbit MQ Setup
  hosts: all
  become: true
  tasks:
    - name: rabbitmq erlang rpm 
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: rabbitmq server rpm 
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install the rabbit mq
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: installed

    - name: Enable and restart rabbitmq
      ansible.builtin.systemd_service:
        name: rabbitmq-server
        state: restarted
        enabled: true
    - name: Add application user 
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
