- name: Set Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Install the latest version of Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy roboshop config file into default.d 
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Recursively remove directory html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a HTML directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
    dest: /usr/share/nginx/html
    remote_src: yes
    
- name: Enable and restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true

   
- name: create nginx prometheus exporter directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: restarted

- name: Download exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: nginx prometheus exporter service
  ansible.builtin.copy:
    src: nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: restart nginx prometheus service
  ansible.builtin.systemd_service:
    name: nginx_exporter
    state: restarted
    enabled: true
      

