
- name: mysql module disable
  ansible.builtin.shell: dnf module disable mysql -y 

- name: Copy mysql repo  into default.d 
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install the latest version of Mysql
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: Enable and restart mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true
    
- name: mysql set password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
