- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy alert configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted