
- name: Copy mongo repo file into repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install the mongodb-org-shell
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed

- name: Load schema into mongodb
  ansible.builtin.shell: mongo --ssl --host "{{lookup('amazon.aws.aws_ssm','docdb.{{env}}.endpoint',region='us-east-1')}}":27017 --sslCAFile global-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js
 